### ISSUE TITLE
Add examples for Camera and VideoCamera

### ISSUE THREAD

**Issue by jaller94** [mozilla-iot/virtual-things-adapter#19]
Please add examples for the new capabilities [Camera](https://iot.mozilla.org/schemas/#Camera) and [VideoCamera](https://iot.mozilla.org/schemas/#VideoCamera).

**Comment by hobinjk** [comment]
https://github.com/mrstegeman/photo-cycler-webthing/ is a good example of serving images but I'm not sure what the best way to create a full VideoCamera virtual thing.

@mrstegeman Any ideas? (or maybe that code which called ffmpeg on a demo file)

**Comment by mrstegeman** [comment]
Yeah, I considered adding a sample image and video file. We'd have to figure out how to serve up the video on a loop.

**Comment by mrstegeman** [comment]
Maybe this: https://video.stackexchange.com/a/17389
