### ISSUE TITLE
Add more than ON virtual ON/OFF switch

### ISSUE THREAD

**Issue by arfrater** [mozilla-iot/virtual-things-adapter#26]
Is it possible to add more than one virtual switch to control a group of physical switches

**Comment by madb1lly** [comment]
This adapter provides a way to add more virtual things than the ones which are provided by default. I think the way to do it is to configure a new virtual thing by going to Settings > Add-Ons > Configure on the Virtual Things and here you can define a new virtual thing.

However, this is not well documented and I am having difficulty getting it to work.

**Comment by mrstegeman** [comment]
Yes, this is supported by adding custom things.
