### ISSUE TITLE
Default disappears

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/virtual-things-adapter#30]
When opening the options page again, the **default** value is not remembered, and must be entered again.

**Comment by mrstegeman** [comment]
After you saved, or did you just refresh?

**Comment by flatsiedatsie** [comment]
After a save. The other values _are_ remembered. Just not the `default` one.

**Comment by mrstegeman** [comment]
I cannot seem to reproduce this. Can you give me exact set of steps, including values (and browser)?
