### ISSUE TITLE
Documentation for creating custom Virtual Thing

### ISSUE THREAD

**Issue by imhavoc-classic** [mozilla-iot/virtual-things-adapter#43]
Is there any documentation for creating a custom Virtual Thing? I How To or a Walkthrough (preferably both) would be very helpful.

**Comment by mrstegeman** [comment]
You're really just creating a [thing description](https://iot.mozilla.org/wot/), using the available [schemas](https://iot.mozilla.org/schemas/), if desired. The fields in the add-on config map directly to those in the thing description.

**Comment by imhavoc-classic** [comment]
Creating a virtual on/off switch seems easy enough:
![image](https://user-images.githubusercontent.com/56138026/66244913-eff1ea80-e6c7-11e9-9070-5aa228d34940.png)

but....

![image](https://user-images.githubusercontent.com/56138026/66244989-46f7bf80-e6c8-11e9-934d-6dfeaa7cc0e2.png)
![image](https://user-images.githubusercontent.com/56138026/66244995-4e1ecd80-e6c8-11e9-881d-2797df0551d9.png)
![image](https://user-images.githubusercontent.com/56138026/66245009-5a0a8f80-e6c8-11e9-9329-a29b754b6384.png)

It's not clear to the initiated what goes where. What if I set up this for a friend or family member and they want me to walk them through creating a virtual whatsit over the phone?

**Comment by mrstegeman** [comment]
The error messages at the top tell you what's going on.
* `name` must not be empty
* `@type` must not be empty if present
* `name` (for the property) must not be empty
* `title` (for the property) must not be empty
* `type` (for the property) is not set

Here's what you should have:
![Screenshot_2019-10-04 WebThings Gateway](https://user-images.githubusercontent.com/457381/66245389-fbd6b000-e6b9-11e9-8b0f-145346288902.png)
![Screenshot_2019-10-04 WebThings Gateway(1)](https://user-images.githubusercontent.com/457381/66245390-fc6f4680-e6b9-11e9-8734-980df3c493bc.png)
![Screenshot_2019-10-04 WebThings Gateway(2)](https://user-images.githubusercontent.com/457381/66245391-fc6f4680-e6b9-11e9-852c-c6dfb00bbbc9.png)
