### ISSUE TITLE
Virtual Button with PIN

### ISSUE THREAD

**Issue by alini76** [mozilla-iot/virtual-things-adapter#50]
I tried to add this to my webthings, but:
1 - It looks like it has a preset 1234 PIN - How can I change this PIN?
2 - I click on the button, but it does not require the PIN. Is this behavior normal?

**Comment by mrstegeman** [comment]
A lot of these devices are really just meant for testing various features of the gateway, including this one (I assume you're actually referring to "Virtual On/Off Switch (with PIN)".

1. You can't.
2. The PIN is only used for pairing.
