### ISSUE TITLE
Programmaticly add virtual things

### ISSUE THREAD

**Issue by rickiesmooth** [mozilla-iot/virtual-things-adapter#54]
Is there a way to reuse the virtual thing adapter in another add on? I want to create a dropdown where the user can select a virtual thing, and add it to the things (like you would when you'd pair it).

**Comment by mrstegeman** [comment]
Sure, it's possible, but can I ask what the use case is?

**Comment by rickiesmooth** [comment]
I'm making a UI extension to group my lights where I want to use virtual things as control switches for the groups. The way it would work is:
 * Creating a group
   * User navigates to https://gateway.local/extensions/group-extension from menu
   * Adds name for group
   * select things (returned from `window.API.getThings`) to add to group 
   * select control switch from dropdown (e.g. `virtual-dimmable-light` from virtual-things-adapter)
   * user submits, and my `APIHandler` will
     *  programmaticly add the control switch to my things
     *  store the group as my addon's config in the db (associated things id's, group name, control switch thing id)

* Controlling the group
  * User navigates to https://gateway.local/extensions/group-extension from menu
  * UI extension retrieves groups returned from the addon's db config through `APIHandler`
  * UI extension displays groups which link to the virtual thing page (/things/virtual-things-0)
  * User clicks group and follows link to virtual thing page
  * controls virtual thing
  * through the websocket API I would check if thing that is updated is control switch of a group, and if so, sync things associated to that group

This way, in the UI I would not have to control 6 different lights.

Also, when there will be voice support I could just say: "dim kitchen lights" and my kitchen lights would dim. (where "kitchen lights" would be control switch thing name and group name )

I have a rough first version of this if you'd need more info. Does this approach make sense? Or do you see a better way of building this?

**Comment by mrstegeman** [comment]
Ok, I see what you're doing. That seems like a reasonable workaround for our current lack of groups.

So, as I said, it would be possible to do what you're asking, but I wouldn't really recommend it. I would instead take what's in this adapter and strip it down to the bare minimum.
* Only support OnOffSwitch (or a basic Light). You could add color, level, etc. if you really need to.
* Allow the user to specify the names of their groups in your add-on config.
* Create those devices for them. All they'd have to do is add them the normal way in the UI.

Why?
1. You're going to need to have the user generate an OAuth token in order to control other lights.
2. However, that token only gives you access to existing things. It won't let you use other gateway functionality, such as creating devices.
3. So, you'd have to either instruct the user on how to open up dev tools and find their user token, or rip it off via your extension (do not do this).

**Comment by rickiesmooth** [comment]
@mrstegeman thank you for your feedback on my idea and mentioning the mercy of the user ;), now I'm stripping down the adapter to the bare minimum and still have a couple of doubts (let me know if I should move my question somewhere else).

If I just want to use my group addon for myself I can quickly hack something together that would add the `virtual-thing-switch` programmatically by using `window.API.addThing` or something, and on the server control my devices by reading/storing a user token. But I assume this wouldn't be according to your add on guidelines/policies seen the UX/security issues.

Because I'd hope to add my addon to the addon-list and the ui-extensions are quit new, I'd like to make sure that it's correct.

Right now I have the following in mind:
When the users create a group, they can explicitly add a `virtual-thing-switch` from the pairing view. Similar to how a virtual thing broadcasts itself, 

```
  startPairing() {
    // if there's a group without an associated virtual-thing-switch
    // it broadcasts a thing with all the shared properties of the group
    this.addVirtualThingSwitch();
  }
```

I'd preferably control the groups devices from my `apiHandler` or server and not from the client, but that complicates the authorization part (maybe add a Local Token Service to my addon settings?)

**Comment by mrstegeman** [comment]
I'd recommend starting with something like the [pulse-adapter](https://github.com/mozilla-iot/pulse-adapter/blob/master/pulse-adapter.js), which creates a user-specified list of "pulses" (virtual on/off switches), which can then be controlled by the UI. You'll just need to replace the actual pulse logic with your own, which will use the Web Thing API to control the other devices (with an OAuth token, which the user will have to provide you).

If you look at the [azure-iot-bridge](https://github.com/tim-hellhake/azure-iot-bridge), you can get a good idea of how to get the OAuth token and control other devices (Tim even has a webthing-client library you could use).

So, overview:
1. Create your Extension.
    * This will be used to:
        1. Show the user their groups.
        2. Allow the user to add/remove groups. This part is optional. Other add-ons do this via the add-on config screen, but doing it in the extension might be nicer. If you do it this way, you could use `window.API.addThing()` and `window.API.removeThing()` yourself, which would prevent the user from having to manually add their virtual devices via the Add Things screen.
2. Create your APIHandler.
    * This will be used to interface with your extension, providing any necessary back-end logic that is not already provided via `window.API`.
3. Create your Adapter.
    * This will be used to do the actual device control.

**Comment by rickiesmooth** [comment]
those are great resources, thank you so much for your advice! Hope to submit my adapter soon :)
